apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 labels:
   template: postgresql-persistent-template01
 name: postgresql
 spec:
   spec:
       accessModes:
       - ReadWriteOnce 
       resources:
         requests:
           storage: 2Gi
 
